services:
  cli:
    build: "cli"
    image: cli_image
    restart: always
    container_name: cli
    networks:
      vpnnetwork:
        ipv4_address: ${CLI_IP}
  ldap:
    build: "ldap"
    image: ldap_image
    restart: always
    container_name: ldap
    networks:
      vpnnetwork:
        ipv4_address: ${LDAP_IP}
  bind9:
    build: "bind9"
    image: bind9_image
    restart: always
    container_name: bind9
    privileged: true
    networks:
      vpnnetwork:
        ipv4_address: ${BIND9_IP}
    volumes:
      - bind:/etc/bind
  php-fpm:
    build: "php-fpm-ondemand"
    image: php-fpm-ondemand_image
    restart: always
    container_name: php-fpm-ondemand
    privileged: true
    networks:
      vpnnetwork:
        ipv4_address: ${PHPFPM_IP}
    volumes:
      - www:/var/www/html
  nginx:
    build: "nginx-ondemand"
    image: nginx-ondemand_image
    restart: always
    container_name: nginx-ondemand
    privileged: true
    networks:
      vpnnetwork:
        ipv4_address: ${NGINX_IP}
    volumes:
      - www:/var/www/html
      - conf.d:/etc/nginx/conf.d
      - http.d:/etc/nginx/http.d
  ocserv:
    build: "ocserv"
    image: ocserv_image
    restart: always
    container_name: ocserv
    privileged: true
    networks:
      vpnnetwork:
        ipv4_address: ${OCSERV_IP}
    hostname: www.example.com
    ports:
      - 4444:443/udp
      - 4444:443
    volumes:
      - ocserv:/etc/ocserv
    environment:
      - DNSIP=172.20.0.10
      - CA_CN=VPN CA
      - CA_ORG=Big Corp
      - CA_DAYS=365
      - SRV_CN=www.example.com
      - SRV_ORG=Nexttop
      - SRV_DAYS=365
networks:
  vpnnetwork:
    name: vpnnetwork
    driver: bridge
    ipam:
     config:
       - subnet: ${NETWORK_SUBNET}
         gateway: ${NETWORK_GETWAY}
volumes:
  www:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_DATA_PATH}/nginx/www
  conf.d:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_DATA_PATH}/nginx/conf.d
  http.d:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_DATA_PATH}/nginx/http.d
  bind:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_DATA_PATH}/bind
  ocserv:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_DATA_PATH}/ocserv