services:
  php-fpm:
    build: "php-fpm"
    image: php-fpm_image
    restart: always
    container_name: php-fpm
    privileged: true
    networks:
      vpnnetwork:
        ipv4_address: ${PHPFPM_IP}
    volumes:
      - www:/var/www/html
  nginx:
    build: "nginx"
    image: nginx_image
    restart: always
    container_name: nginx
    privileged: true
    ports:
      - 8080:8080
    networks:
      vpnnetwork:
        ipv4_address: ${NGINX_IP}
    volumes:
      - www:/var/www/html
      - conf.d:/etc/nginx/conf.d
      - http.d:/etc/nginx/http.d
networks:
  vpnnetwork:
    name: webnetwork
    driver: bridge
    ipam:
     config:
       - subnet: ${NETWORK_SUBNET}
         gateway: ${NETWORK_GETWAY}
volumes:
  www:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_DATA_PATH}/nginx/www
  conf.d:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_DATA_PATH}/nginx/conf.d
  http.d:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_DATA_PATH}/nginx/http.d