FROM coturn/coturn:alpine
MAINTAINER nexttop <nexttop@osxx.com>
LABEL Description="Lightweight container with coturn"

# Setup document root
WORKDIR /

#RUN apk add --no-cache \
#  curl \
#  && rm -rf /var/cache/apk/*


#COPY docker-entrypoint.sh /entrypoint.sh
#ENTRYPOINT ["/entrypoint.sh"]


# Expose the port nginx is reachable on
#EXPOSE 3478

#CMD []